### ISSUE TITLE
Question: is it searching only for direct dependant  ?

### ISSUE THREAD

**Issue by ainthek** [dependents/node-dependents#79]
I would like to search all dependants in the tree that depends on my file and those who depends on them etc..

thanx

**Comment by mrjoelkemp** [comment]
Thanks for your question! Yes, it current searches for direct dependents. Sounds like you want to view the path(s) to a particular  module starting from relevant roots all the way down to the module in question. 

That could likely get built into https://github.com/pahen/madge if all you're looking for is a view of the paths. Mind asking there? There are no plans to build that into Dependents.
